### ISSUE TITLE
wpt install firefox browser fails on macOS

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#9090]
```
$ ./wpt install firefox browser
Now installing firefox browser...
Traceback (most recent call last):
  File "../../wpt", line 5, in <module>
    wpt.main()
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/install.py", line 30, in run
    install(browser, kwargs["component"], destination)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/install.py", line 41, in install
    getattr(subclass(), method)(dest=destination)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/browser.py", line 116, in install
    resp = self.get_from_nightly("<a[^>]*>(firefox-\d+\.\d(?:\w\d)?.en-US.%s\.tar\.bz2)" % self.platform_string())
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/browser.py", line 107, in get_from_nightly
    filename = re.compile(pattern).search(index.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

There indeed appear to be no macOS builds packaged as `.tar.bz2` on https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/

**Comment by Cactusmachete** [comment]
Similar to this issue https://github.com/w3c/web-platform-tests/issues/7996
Fixed this in https://github.com/w3c/web-platform-tests/pull/9748

**Comment by gsnedders** [comment]
Hmm, this seems to still fail, but seems to be a build issue:

```
(py2-env) pnin:web-platform-tests gsnedders$ ./wpt install firefox browser
Now installing firefox browser...
INFO:mozdownload.scraper:Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
INFO:mozdownload.scraper:Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2018/03/
INFO:mozdownload.scraper:Found 1 build: 2018-03-08-10-01-21-mozilla-central
INFO:mozdownload.scraper:Selected build: 2018-03-08-10-01-21-mozilla-central
INFO:mozdownload.scraper:Downloading from: https://archive.mozilla.org/pub/firefox/nightly/2018/03/2018-03-08-10-01-21-mozilla-central/firefox-60.0a1.en-US.mac.dmg
INFO:mozdownload.scraper:Saving as: /Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/_venv/2018-03-08-10-01-21-mozilla-central-firefox-60.0a1.en-US.mac.dmg
100% |##################################################################| Time: 0:00:06  10.74 MB/s
hdiutil: attach failed - no mountable file systems
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/install.py", line 30, in run
    install(browser, kwargs["component"], destination)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/install.py", line 41, in install
    getattr(subclass(), method)(dest=destination)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/browser.py", line 128, in install
    mozinstall.uninstall(dest+'/Firefox Nightly.app')
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/_venv/lib/python2.7/site-packages/mozinstall/mozinstall.py", line 215, in uninstall
    'installation folder "%s" exists.' % install_folder
AssertionError: installation folder "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/_venv/Firefox Nightly.app" exists.
```

That said, we shouldn't be asserting here because we shouldn't be trying to uninstall unconditionally when the install fails.

**Comment by gsnedders** [comment]
Oh the install failing there is my fault, but still, it shouldn't uninstall unconditionally.

And test_run_firefox and test_install_firefox still fail on macOS:

```
________________________________________ test_run_firefox _________________________________________

manifest_dir = '/var/folders/vz/49fjtt155dd0f745pgdvkg9h0000gn/T/tmpbQgOlI'

    @pytest.mark.slow
    @pytest.mark.remote_network
    @pytest.mark.xfail(sys.platform == "win32",
                       reason="Tests currently don't work on Windows for path reasons")
    def test_run_firefox(manifest_dir):
        # TODO: It seems like there's a bug in argparse that makes this argument order required
        # should try to work around that
        if is_port_8000_in_use():
            pytest.skip("port 8000 already in use")
    
        os.environ["MOZ_HEADLESS"] = "1"
        try:
            fx_path = os.path.join(wpt.localpaths.repo_root, "_venv", "firefox")
            if os.path.exists(fx_path):
                shutil.rmtree(fx_path)
            with pytest.raises(SystemExit) as excinfo:
                wpt.main(argv=["run", "--no-pause", "--install-browser", "--yes",
                               "--metadata", manifest_dir,
>                              "firefox", "/dom/nodes/Element-tagName.html"])

tests/test_wpt.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
wpt.py:132: in main
    rv = script(*args, **kwargs)
run.py:438: in run
    **kwargs)
run.py:418: in setup_wptrunner
    setup_cls.setup(kwargs)
run.py:157: in setup
    self.setup_kwargs(kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tools.wpt.run.Firefox object at 0x105b87f50>
kwargs = {'restart_on_unexpected': True, 'this_chunk': 1, 'tests_root': '/Users/gsnedde...one, 'sauce_build': None, 'reftest_screenshot': 'unexpected', 'ssl_type': None}

    def setup_kwargs(self, kwargs):
        if kwargs["binary"] is None:
            binary = self.browser.find_binary()
            if binary is None:
                raise WptrunError("""Firefox binary not found on $PATH.
    
>   Install Firefox or use --binary to set the binary path""")
E               WptrunError: Firefox binary not found on $PATH.
E               
E               Install Firefox or use --binary to set the binary path

run.py:170: WptrunError
-------------------------------------- Captured stdout call ---------------------------------------
 0:00.41 INFO Installing browser
______________________________________ test_install_firefox _______________________________________

    @pytest.mark.slow
    @pytest.mark.remote_network
    @pytest.mark.xfail(sys.platform == "win32",
                       reason="Tests currently don't work on Windows for path reasons")
    def test_install_firefox():
        fx_path = os.path.join(wpt.localpaths.repo_root, "_venv", "firefox")
        if os.path.exists(fx_path):
            shutil.rmtree(fx_path)
        with pytest.raises(SystemExit) as excinfo:
            wpt.main(argv=["install", "firefox", "browser"])
        assert excinfo.value.code == 0
>       assert os.path.exists(fx_path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x10340a578>('/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/_venv/firefox')
E        +    where <function exists at 0x10340a578> = <module 'posixpath' from '/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/.tox/py27/lib/python2.7/posixpath.pyc'>.exists
E        +      where <module 'posixpath' from '/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/.tox/py27/lib/python2.7/posixpath.pyc'> = os.path

tests/test_wpt.py:132: AssertionError
-------------------------------------- Captured stdout call ---------------------------------------
Now installing firefox browser...
-------------------------------------- Captured stderr call ---------------------------------------
INFO:mozdownload.scraper:Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
INFO:mozdownload.scraper:Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
INFO:mozdownload.scraper:Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2018/03/
INFO:mozdownload.scraper:Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2018/03/
INFO:mozdownload.scraper:Found 1 build: 2018-03-08-10-01-21-mozilla-central
INFO:mozdownload.scraper:Found 1 build: 2018-03-08-10-01-21-mozilla-central
INFO:mozdownload.scraper:Selected build: 2018-03-08-10-01-21-mozilla-central
INFO:mozdownload.scraper:Selected build: 2018-03-08-10-01-21-mozilla-central
INFO:mozdownload.scraper:Downloading from: https://archive.mozilla.org/pub/firefox/nightly/2018/03/2018-03-08-10-01-21-mozilla-central/firefox-60.0a1.en-US.mac.dmg
INFO:mozdownload.scraper:Downloading from: https://archive.mozilla.org/pub/firefox/nightly/2018/03/2018-03-08-10-01-21-mozilla-central/firefox-60.0a1.en-US.mac.dmg
INFO:mozdownload.scraper:Saving as: /Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/_venv/2018-03-08-10-01-21-mozilla-central-firefox-60.0a1.en-US.mac.dmg
INFO:mozdownload.scraper:Saving as: /Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/_venv/2018-03-08-10-01-21-mozilla-central-firefox-60.0a1.en-US.mac.dmg
100% |##############################################| Time: 0:00:02  23.64 MB/s
---------------------------------------- Captured log call ----------------------------------------
scraper.py                 411 INFO     Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
scraper.py                 458 INFO     Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2018/03/
scraper.py                 329 INFO     Found 1 build: 2018-03-08-10-01-21-mozilla-central
scraper.py                 494 INFO     Selected build: 2018-03-08-10-01-21-mozilla-central
scraper.py                 266 INFO     Downloading from: https://archive.mozilla.org/pub/firefox/nightly/2018/03/2018-03-08-10-01-21-mozilla-central/firefox-60.0a1.en-US.mac.dmg
scraper.py                 267 INFO     Saving as: /Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/_venv/2018-03-08-10-01-21-mozilla-central-firefox-60.0a1.en-US.mac.dmg
```

**Comment by Cactusmachete** [comment]
The one in test_run_firefox should be arising from the fact that find_binary() currently only looks for the firefox binary installed in PATH, not the one in _venv. Pretty sure I've fixed this in https://github.com/w3c/web-platform-tests/pull/9900 though. 

The assertion error in test_install_firefox happens because firefox is installed to a different path in Mac than linux, so we'll have to put a condition for that as well.

**Comment by Cactusmachete** [comment]
In fact, test_run_firefox will fail for the same reason as install, even with the find_binary function fixed.

**Comment by Cactusmachete** [comment]
I think we can mark this as closed since https://github.com/w3c/web-platform-tests/pull/9900 was merged.
